/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shapes;

/**
 *
 * @author tdalabrador
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaneShapes = new javax.swing.JTabbedPane();
        PanelTriangle = new javax.swing.JPanel();
        lblRectangleLength4 = new javax.swing.JLabel();
        txtTriangleBase = new javax.swing.JTextField();
        lblUnitsLength1 = new javax.swing.JLabel();
        lblRectangleLength5 = new javax.swing.JLabel();
        txtTriangleHeight = new javax.swing.JTextField();
        lblUnitsWidth1 = new javax.swing.JLabel();
        lblRectangleLength6 = new javax.swing.JLabel();
        txtTriangleArea = new javax.swing.JTextField();
        lblUnitsSquared1 = new javax.swing.JLabel();
        PanelRectangle = new javax.swing.JPanel();
        lblUnitsSquared = new javax.swing.JLabel();
        txtRectangleLength = new javax.swing.JTextField();
        lblRectangleLength1 = new javax.swing.JLabel();
        lblRectangleLength2 = new javax.swing.JLabel();
        txtRectangleWidth = new javax.swing.JTextField();
        txtRectangleArea = new javax.swing.JTextField();
        lblRectangleLength3 = new javax.swing.JLabel();
        lblUnitsWidth = new javax.swing.JLabel();
        lblUnitsLength = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Area Calculator");

        PanelTriangle.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelTriangleComponentShown(evt);
            }
        });

        lblRectangleLength4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblRectangleLength4.setText("Base");

        txtTriangleBase.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        txtTriangleBase.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTriangleBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTriangleBaseKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTriangleBaseKeyTyped(evt);
            }
        });

        lblUnitsLength1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUnitsLength1.setText("units");

        lblRectangleLength5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblRectangleLength5.setText("Height");

        txtTriangleHeight.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        txtTriangleHeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTriangleHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTriangleHeightKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTriangleHeightKeyTyped(evt);
            }
        });

        lblUnitsWidth1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUnitsWidth1.setText("units");

        lblRectangleLength6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblRectangleLength6.setText("Area");

        txtTriangleArea.setBackground(new java.awt.Color(239, 239, 239));
        txtTriangleArea.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        txtTriangleArea.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblUnitsSquared1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUnitsSquared1.setText("units²");

        javax.swing.GroupLayout PanelTriangleLayout = new javax.swing.GroupLayout(PanelTriangle);
        PanelTriangle.setLayout(PanelTriangleLayout);
        PanelTriangleLayout.setHorizontalGroup(
            PanelTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTriangleLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(PanelTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRectangleLength5)
                    .addComponent(lblRectangleLength6)
                    .addComponent(lblRectangleLength4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(PanelTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTriangleLayout.createSequentialGroup()
                        .addComponent(txtTriangleArea, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUnitsSquared1))
                    .addGroup(PanelTriangleLayout.createSequentialGroup()
                        .addComponent(txtTriangleHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUnitsWidth1))
                    .addGroup(PanelTriangleLayout.createSequentialGroup()
                        .addComponent(txtTriangleBase, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUnitsLength1)))
                .addGap(64, 64, 64))
        );
        PanelTriangleLayout.setVerticalGroup(
            PanelTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTriangleLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(PanelTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTriangleBase, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lblRectangleLength4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUnitsLength1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTriangleHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(lblUnitsWidth1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblRectangleLength5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRectangleLength6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTriangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTriangleArea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUnitsSquared1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(122, 122, 122))
        );

        PaneShapes.addTab("Triangle", PanelTriangle);

        PanelRectangle.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelRectangleComponentShown(evt);
            }
        });

        lblUnitsSquared.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUnitsSquared.setText("units²");

        txtRectangleLength.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        txtRectangleLength.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRectangleLength.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRectangleLengthKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRectangleLengthKeyTyped(evt);
            }
        });

        lblRectangleLength1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblRectangleLength1.setText("Width");

        lblRectangleLength2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblRectangleLength2.setText("Area");

        txtRectangleWidth.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        txtRectangleWidth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRectangleWidth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRectangleWidthKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRectangleWidthKeyTyped(evt);
            }
        });

        txtRectangleArea.setBackground(new java.awt.Color(239, 239, 239));
        txtRectangleArea.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        txtRectangleArea.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblRectangleLength3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblRectangleLength3.setText("Length");

        lblUnitsWidth.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUnitsWidth.setText("units");

        lblUnitsLength.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblUnitsLength.setText("units");

        javax.swing.GroupLayout PanelRectangleLayout = new javax.swing.GroupLayout(PanelRectangle);
        PanelRectangle.setLayout(PanelRectangleLayout);
        PanelRectangleLayout.setHorizontalGroup(
            PanelRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRectangleLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(PanelRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRectangleLength1)
                    .addComponent(lblRectangleLength2)
                    .addComponent(lblRectangleLength3))
                .addGap(38, 38, 38)
                .addGroup(PanelRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRectangleLayout.createSequentialGroup()
                        .addComponent(txtRectangleArea, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUnitsSquared))
                    .addGroup(PanelRectangleLayout.createSequentialGroup()
                        .addComponent(txtRectangleWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUnitsWidth))
                    .addGroup(PanelRectangleLayout.createSequentialGroup()
                        .addComponent(txtRectangleLength, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblUnitsLength)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        PanelRectangleLayout.setVerticalGroup(
            PanelRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRectangleLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(PanelRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRectangleLength, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lblRectangleLength3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUnitsLength, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRectangleWidth, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(lblUnitsWidth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblRectangleLength1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRectangleLength2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRectangleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRectangleArea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUnitsSquared, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(122, 122, 122))
        );

        PaneShapes.addTab("Rectangle", PanelRectangle);

        jLabel1.setText("Area Calculator v1.0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PaneShapes)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PaneShapes, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRectangleLengthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectangleLengthKeyTyped
        this.preventNAN(evt); 
    }//GEN-LAST:event_txtRectangleLengthKeyTyped

    private void txtRectangleWidthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectangleWidthKeyTyped
        this.preventNAN(evt);        
    }//GEN-LAST:event_txtRectangleWidthKeyTyped

    private void PanelRectangleComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelRectangleComponentShown
        // Disable edited of txtRectangleArea
        txtRectangleArea.setEditable(false);
    }//GEN-LAST:event_PanelRectangleComponentShown

    private void txtRectangleLengthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectangleLengthKeyReleased
        this.computeRectangleArea();
    }//GEN-LAST:event_txtRectangleLengthKeyReleased

    private void txtRectangleWidthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRectangleWidthKeyReleased
        this.computeRectangleArea();
    }//GEN-LAST:event_txtRectangleWidthKeyReleased

    private void txtTriangleBaseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTriangleBaseKeyReleased
        this.computeTriangleArea();
    }//GEN-LAST:event_txtTriangleBaseKeyReleased

    private void txtTriangleBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTriangleBaseKeyTyped
        this.preventNAN(evt);
    }//GEN-LAST:event_txtTriangleBaseKeyTyped

    private void txtTriangleHeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTriangleHeightKeyReleased
        this.computeTriangleArea();
    }//GEN-LAST:event_txtTriangleHeightKeyReleased

    private void txtTriangleHeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTriangleHeightKeyTyped
        this.preventNAN(evt);
    }//GEN-LAST:event_txtTriangleHeightKeyTyped

    private void PanelTriangleComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelTriangleComponentShown
        txtTriangleArea.setEditable(false);
    }//GEN-LAST:event_PanelTriangleComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }
    
    public void computeRectangleArea(){
                // Create Rectangle Object
        Rectangle rectangle = new Rectangle("white", 1, 1);
        String lengthString = txtRectangleLength.getText();
        String widthString = txtRectangleWidth.getText();
        if(!lengthString.equals("") && !widthString.equals("")){
            
            // Count number of periods entered
            char someChar = '.';
            int count = 0;
            for (int i = 0; i < lengthString.length(); i++) if (lengthString.charAt(i) == someChar) count++;
            
            if (count == 1 || count == 0){
                rectangle.setLength(Double.parseDouble(lengthString));
                rectangle.setWidth(Double.parseDouble(widthString));
                
                try {
                    txtRectangleArea.setText(String.format("%.2f", rectangle.getArea()));
                } catch (NumberFormatException e){
                    // Do nothing
                }
            }
        }
    }
    
    public void computeTriangleArea(){
        // Create Rectangle Object
        Triangle triangle = new Triangle("white", 1, 1);
        String baseString = txtTriangleBase.getText();
        String heightString = txtTriangleHeight.getText();
        if(!baseString.equals("") && !heightString.equals("")){
            
            // Count number of periods entered
            char someChar = '.';
            int count = 0;
            for (int i = 0; i < baseString.length(); i++) if (baseString.charAt(i) == someChar) count++;
            
            if (count == 1 || count == 0){
                triangle.setBase(Double.parseDouble(baseString));
                triangle.setHeight(Double.parseDouble(heightString));
                
                try {
                    txtTriangleArea.setText(String.format("%.2f", triangle.getArea()));
                } catch (NumberFormatException e){
                    // Do nothing
                }
            }
        }
    }
    
    public void preventNAN(java.awt.event.KeyEvent evt){
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != '.'){
            evt.consume();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PaneShapes;
    private javax.swing.JPanel PanelRectangle;
    private javax.swing.JPanel PanelTriangle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRectangleLength1;
    private javax.swing.JLabel lblRectangleLength2;
    private javax.swing.JLabel lblRectangleLength3;
    private javax.swing.JLabel lblRectangleLength4;
    private javax.swing.JLabel lblRectangleLength5;
    private javax.swing.JLabel lblRectangleLength6;
    private javax.swing.JLabel lblUnitsLength;
    private javax.swing.JLabel lblUnitsLength1;
    private javax.swing.JLabel lblUnitsSquared;
    private javax.swing.JLabel lblUnitsSquared1;
    private javax.swing.JLabel lblUnitsWidth;
    private javax.swing.JLabel lblUnitsWidth1;
    private javax.swing.JTextField txtRectangleArea;
    private javax.swing.JTextField txtRectangleLength;
    private javax.swing.JTextField txtRectangleWidth;
    private javax.swing.JTextField txtTriangleArea;
    private javax.swing.JTextField txtTriangleBase;
    private javax.swing.JTextField txtTriangleHeight;
    // End of variables declaration//GEN-END:variables
}
